# Generated by Django 3.1.1 on 2020-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0003_trip_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenrary',
            old_name='Day_number',
            new_name='day_number',
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_location',
            field=models.CharField(choices=[('NR', 'Naran'), ('HN', 'Hunza'), ('SK', 'Skardu')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_location',
            field=models.CharField(choices=[('LHE', 'Lahore'), ('ISB', 'Islamabad')], max_length=100, null=True),
        ),
    ]
