# Generated by Django 3.1.1 on 2020-10-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0005_auto_20201005_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip_project.host'),
        ),
    ]
