# Generated by Django 3.1.1 on 2020-10-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0007_auto_20201009_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_location',
        ),
    ]
