# Generated by Django 3.1.1 on 2020-10-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0008_auto_20201009_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='destination_location_1',
            new_name='destination_location',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_location_1',
            new_name='start_location',
        ),
    ]
