# Generated by Django 3.1.1 on 2020-10-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0009_auto_20201009_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
