# Generated by Django 3.1.1 on 2020-10-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0010_auto_20201009_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Locations',
        ),
    ]
