# Generated by Django 3.1.1 on 2020-10-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0013_auto_20201009_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='locattion_name',
            new_name='location_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_location',
        ),
    ]
