# Generated by Django 3.1.1 on 2020-10-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0014_auto_20201009_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip_project.location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='trip_project.location'),
        ),
    ]
