# Generated by Django 3.1.1 on 2020-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0015_auto_20201009_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=100),
        ),
    ]
