# Generated by Django 3.1.1 on 2020-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0022_siteconfigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfigration',
            name='add_trip_url',
            field=models.CharField(default='Null', max_length=150),
        ),
    ]
