# Generated by Django 3.1.1 on 2020-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0023_siteconfigration_add_trip_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfigration',
            name='add_trip_url',
        ),
        migrations.AddField(
            model_name='siteconfigration',
            name='values',
            field=models.JSONField(default={}),
        ),
    ]
