# Generated by Django 3.1.1 on 2020-12-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0024_auto_20201201_1109_squashed_0032_auto_20201214_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripschedule',
            old_name='over_ridden_price',
            new_name='price_override',
        ),
    ]
