# Generated by Django 3.1.1 on 2020-12-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0026_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.CharField(default=1, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status_change_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
