# Generated by Django 3.1.1 on 2020-12-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0029_auto_20201211_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Over_ridden_price', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_project.trip')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
