# Generated by Django 3.1.1 on 2020-12-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0030_auto_20201211_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
