# Generated by Django 3.1.1 on 2020-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_project', '0031_auto_20201214_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripschedule',
            old_name='Over_ridden_price',
            new_name='over_ridden_price',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
